### ISSUE TITLE
Pass on first turn 

### ISSUE THREAD

**Issue by gstone21** [hgwelliver/EuchreGameStateProject#3]
1. Start game
2. Press pass
3. Bug found: Pass works and does not let you play card after pressing pass, but you should not be able to pass on your first turn.

**Comment by nieland22** [comment]
This is a newfound bug. Thank you for the find. The user should be able to play a card when the game opens, and pressing the pass button should not let the user not play a card. We will fix this issue.

**Comment by hgwelliver** [comment]
Fixed. No longer an issue during card play.
