### ISSUE TITLE
Null Card Causes Game To Crash 

### ISSUE THREAD

**Issue by nieland22** [hgwelliver/EuchreGameStateProject#6]
Sometimes a method that does not take in a null card receives a null card which causes the game to crash. We need to find where the null card is coming from.

**Comment by hgwelliver** [comment]
sometimes only 4 cards are dealt to a player. if this player is a computer, the player attempts to play a fifth card (which is null) and the game will crash.

**Comment by hgwelliver** [comment]
finally fixed !
